mode: live
account:
  managed_fraction: 0.80          # 80% of total equity
  base_currency: USD
symbols: [BTCUSD, SOLUSD]
timeframes: 
  scan: 1m
  trade: 5m
macd: 
  fast: 12
  slow: 26
  signal: 9
ema: 
  len: 200
atr_len: 14
whales: 
  single_trade: 250000
  window_notional: 1000000
  imbalance: 0.65
  window_min: 1
risk:
  per_trade: 0.10                 # 10%
  daily_stop: 0.30                # 30%
  max_symbol_alloc: 0.50          # allow up to 50% of managed equity per symbol
exits:
  atr_stop: 1.5
  atr_tp: 2.0
  time_bars: 30
  trail_atr: 1.0
limits:
  max_trades_day: 20
  max_consecutive_losses: 4
cooldown_minutes_after_loss_streak: 120

